coverage:
  status:
    project:
      default:
        informational: false
        target: auto
    patch:
      default:
        informational: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default

flags:
  unittests:
    paths:
      - pkg/auth
      - pkg/ctx
      - pkg/db
      - pkg/errors
      - pkg/httpx
      - pkg/middleware
      - pkg/observability