run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - gosimple
    - govet
    - ineffassign
    - revive
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unused

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0