version: 2

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - staticcheck
    - gosimple
    - govet
    - ineffassign
    - revive
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unused

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0